# Generated by Django 5.1.3 on 2024-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta_Productos',
            fields=[
                ('id_venta', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_trabajador', models.PositiveSmallIntegerField()),
                ('id_cliente', models.PositiveSmallIntegerField()),
                ('id_producto', models.PositiveSmallIntegerField()),
                ('fecha_venta', models.DateField()),
                ('total', models.CharField(max_length=50)),
            ],
        ),
    ]
