# Generated by Django 5.1.3 on 2024-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id_corte', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_corte', models.CharField(max_length=50)),
                ('tipo_corte', models.CharField(max_length=50)),
                ('precio', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
