# Generated by Django 5.1.3 on 2024-11-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('num_telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_ne', models.DateField(max_length=50)),
                ('fecha_ing', models.DateField(max_length=50)),
            ],
        ),
    ]
