# Generated by Django 5.1 on 2024-11-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('metodo_p', models.CharField(max_length=50)),
                ('tipo_cort', models.CharField(max_length=50)),
                ('tipo_cab', models.CharField(max_length=50)),
                ('fecha_nc', models.CharField(max_length=50)),
            ],
        ),
    ]
